---

- hosts: all
  become: true
  gather_facts: true
  roles:
    - moscow_region

- hosts: allservers
  become: true
  gather_facts: true
  roles:
    - role: community.zabbix.zabbix_agent
      vars:
        zabbix_agent_server: server.noname.ru
        
- hosts: cloud_client
  become: true
  gather_facts: true
  roles:
    - role: cron_copy_files

- hosts: cloud_client # указываем имя хоста на котором будут созданы роли
  become: true # обязательно указываем параметр который выполнит создание ролей как root пользователь и потребуется ввести пароль
  gather_facts: true # оставляем данный параметр, он служит для сбора данных о переменных и информации о системе на удаленном host-е.
  roles: # здесь мы указываем нужную нам роль из нами созданных, в данном случае role-ports.
    - role: role-ports # имя роли